device: "auto"
train:
  - _target_: src.metrics.ExampleMetric
    metric:
      _target_: torchmetrics.classification.MulticlassAccuracy
      num_classes: 2
    device: ${metrics.device}
    name: "Accuracy"
inference: []
